# Github Actions Workflow to deploy a Python Lambda CDK stack
# Version 2021-09-01
# https://gist.github.com/kjpgit/f61037640f418f699496c5c490e2f22c

name: Auto Deploy
on: 
 push:
    branches:
      - main

# Don't allow concurrent deploys on a branch
# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #       - name: Set Env Vars
      #         run: |
      #           if test ${{ github.ref }} = 'refs/heads/production'; then
      #             echo "STACK_NAME=production-microservice" >> $GITHUB_ENV
      #             echo "AWS_ROLE=arn:aws:iam::12345:role/OrganizationAccountAccessRole" >> $GITHUB_ENV
      #           else
      #             echo "Unknown branch"
      #             exit 1
      #           fi

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.FSL_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.FSL_AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

